I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 78, in script
    elder "We gather here to honor the sacred bond between our people and the land. This protest is our stand against the hydroelectric dam."
Exception: Sayer 'elder' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 78, in script
    elder "We gather here to honor the sacred bond between our people and the land. This protest is our stand against the hydroelectric dam."
  File "/Applications/renpy-8.3.2-sdk/renpy/ast.py", line 2573, in execute
    Say.execute(self)
  File "/Applications/renpy-8.3.2-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/renpy-8.3.2-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'elder' is not defined.

macOS-14.6.1-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
Balancing the Flow 1.0
Sat Oct 19 17:38:40 2024
